######################################################################
# Automatically generated by qmake (3.0) Di. Juli 10 09:52:21 2018
######################################################################

TEMPLATE = app
TARGET = fpv
INCLUDEPATH += .
QT += core widgets
CONFIG += c++11
LIBS += -lcurl -lexif

# Input
HEADERS += Exif.h Viewer.h Resolver.h clickablelabel.h
SOURCES += fpv.cpp Exif.cpp Viewer.cpp Resolver.cpp clickablelabel.cpp
